package com.tl.transaction_ledger.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

/**
 * Represents a user account that holds transactions.
 * One account can have many transactions.
 */
@Entity
@Table(name = "accounts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Account {

    /**
     * Primary key for the account.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable name of the account.
     * Example: "Main Account", "Savings Account"
     */
    @Column(nullable = false)
    private String name;

    /**
     * One account can have many transactions.
     * Mapped by the "account" field in Transaction entity.
     */
    @OneToMany(
            mappedBy = "account",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<transaction> transactions;
}
